# This is a basic workflow to help you get started with Actions

name: Android Build CI

# Controls when the workflow will run

on: [push, pull_request, workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel

jobs:

  # This workflow contains a single job called "build"

  build:

    # The type of runner that the job will run on

    runs-on: ubuntu-latest

    

    # Steps represent a sequence of tasks that will be executed as part of the job

    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it

      - uses: actions/checkout@v2

      - uses: krdlab/setup-haxe@v1

        with:

          haxe-version: 4.2.3

          

      - name: Cache haxelib path

        uses: actions/cache@v2

        with:

          path: |

            %HAXELIB_ROOT%

          key: ${{ runner.os }}-android

          

      - name: Setup Android SDK Tools

        uses: android-actions/setup-android@v2.0.2

        

      - name: Setup Java JDK

        uses: actions/setup-java@v2.3.1

        with:

          distribution: 'zulu'

          versión java: '11'

        

      - usos: nttld/setup-ndk@v1

        con:

          Versión ndk: r15c

      # Ejecuta un conjunto de comandos usando el intérprete de comandos

      - nombre: línea de ejecución del script jaja

        ejecutar: |

          mkdir -p "%HAXELIB_ROOT%"

          configuración de haxelib "%HAXELIB_ROOT%"

          haxelib install lime 7.9.0 --quiet

          haxelib instalar openfl --quiet

          haxelib instalar flixel 4.9.0 --quiet

          haxelib instalar hxcpp --quiet

          haxelib ejecuta la configuración de cal

          haxelib ejecuta la configuración de lime ANDROID_SDK $ANDROID_SDK_ROOT

          haxelib ejecuta la configuración de lime ANDROID_NDK_ROOT $ANDROID_NDK_ROOT

          haxelib ejecutar configuración de cal JAVA_HOME $ JAVA_HOME

          haxelib ejecutar lime config ANDROID_SETUP verdadero

          haxelib instalar flixel-tools --quiet

          haxelib instalar flixel-ui --quiet

          haxelib install flixel-addons 2.10.0 --quiet

          haxelib install hscript --quiet

          haxelib git faxe https://github.com/uhrobots/faxe --quiet

          haxelib git polymod https://github.com/MasterEric/polymod.git --quiet

          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc --quiet

          haxelib git extension-webview https://github.com/jigsaw-4277821/extension-webview --quiet

          haxelib git linc_luajit https://github.com/Daninnocent/linc_luajit.git --quiet

          haxelib install actuate 

          haxelib list

          

      - name: Build Log

        run: |

          haxelib run lime setup android

          haxelib run lime build android -final

          

      - uses: actions/upload-artifact@v2

        with:

          name: Android Build

          path: export/release/android/bin/app/build/outputs/apk/debug


































